apiVersion: v1
kind: Service
metadata:
  name: web-html-service
spec:
  selector:
    app: web-html
  type: NodePort  # Hoặc LoadBalancer nếu chạy trên cloud
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # Chọn một port > 30000
